services:
  db:
    container_name: rust-dhcp-db
    restart: always
    image: postgres:13
    networks:
      - dhcp_bridge
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  rust_dhcp_server:
    build:
      context: .
    container_name: rust_dhcp_server
    env_file:
      - .env
    networks:
      dhcp_bridge:
        ipv4_address: 192.168.10.30
    ports:
      - "67:67/udp"
      - "68:68/udp"
    depends_on:
      - db
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - RUST_LOG=info
    privileged: true
    entrypoint: ["/usr/local/bin/wait-for-db.sh", "/usr/local/bin/server"]

  # dhcp_client:
  #   image: busybox
  #   container_name: dhcp_client
  #   depends_on:
  #     - rust_dhcp_server
  #   networks:
  #     dhcp_bridge: {}
  #   entrypoint: ["sh"]
  #   stdin_open: true
  #   tty: true
  #   privileged: true
  #   volumes:
  #     - ./udhcpc-script.sh:/etc/udhcpc/udhcpc-script.sh:ro

  # dhcp_client:
  #   build:
  #     context: ./client_test
  #   networks:
  #     dhcp_bridge:
  #       ipv4_address: 192.168.10.9
  #   stdin_open: true
  #   tty: true
  #   cap_add:
  #     - NET_ADMIN
  #     - NET_RAW

  # dhcp_client_busybox:
  #   image: busybox
  #   container_name: dhcp_client_busybox
  #   networks:
  #     - dhcp_bridge
  #   entrypoint: ["udhcpc", "-i", "eth0", "-f", "-R"]
  #   stdin_open: true
  #   tty: true
  #   cap_add:
  #     - NET_ADMIN
  #     - NET_RAW

  dhcp_client_1:
    image: busybox
    container_name: dhcp_client_1
    networks:
      - dhcp_bridge
    entrypoint: ["udhcpc", "-i", "eth0", "-R"]
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW

  dhcp_client_2:
    image: busybox
    container_name: dhcp_client_2
    networks:
      - dhcp_bridge
    entrypoint: ["udhcpc", "-i", "eth0", "-R"]
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW

  dhcp_client_3:
    image: busybox
    container_name: dhcp_client_3
    networks:
      - dhcp_bridge
    entrypoint: ["udhcpc", "-i", "eth0", "-R"]
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW

  dhcp_client_4:
    image: busybox
    container_name: dhcp_client_4
    networks:
      - dhcp_bridge
    entrypoint: ["udhcpc", "-i", "eth0", "-R"]
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW

volumes:
  postgres_data:

networks:
  dhcp_bridge:
    external: true
